name: Publish docs
permissions:
  contents: read

on:
  workflow_call:
    inputs:
      release_tag:
        description: 'Existing git tag in the format x.x.x'
        required: true
        type: string
  workflow_dispatch:
     inputs:
      release_tag:
        description: 'Existing git tag in the format x.x.x'
        required: true
        type: string

jobs:
  build_docs:
    runs-on: ubuntu-latest
    env:
      RELEASE_TAG: ${{ inputs.release_tag }}
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          ref: ${{ env.RELEASE_TAG }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
          package_json_file: docs_new/package.json
          version: 8
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Install dependencies
        run: pnpm install
        working-directory: ./docs_new
      - name: Build with VitePress
        run: |
          echo "{\"version\":\"${RELEASE_TAG}\"}" > ./.vitepress/version.json
          pnpm docs:build
        working-directory: ./docs_new
      - name: Download the helm index
        run: |
          curl https://github.com/kanisterio/kanister/releases/download/${RELEASE_TAG}/helm_index.yaml -o docs_new/.vitepress/dist/index.yaml
      - name: Upload artifact
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          path: docs_new/.vitepress/dist
          name: docs

  publish_docs:
    needs: build_docs

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      contents: write   # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    env:
      RELEASE_TAG: ${{ inputs.release_tag }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          ref: kanister-docs
      - name: Download artifact
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: docs
      - name: commit_changes
        run: |
          git config --global user.name 'Kasten Production'
          git config --global user.email 'infra@kasten.io'
          git add -A
          git commit -s -m "Update docs to ${RELEASE_TAG}"
      - name: push_changes
        run: git push origin kanister-docs
